### ISSUE TITLE
Gamepads

### ISSUE THREAD

**Issue by RobLoach** [DeXP/nuklear_cross#5]
Nice work on nuiklear_cross! I like the idea.

Not sure if it's something you were looking for, but I needed some gamepad support in Nuklear, so I put together this small API. Seems to take on a similar approach as nuklear_cross so I thought I'd share it with ya https://github.com/robloach/nuklear_gamepad

**Comment by DeXP** [comment]
Thank you for your work. 
Yup, please use 3rd party solutions for the gamepad.
